// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RBPDIS_LAB6.Models;

#nullable disable

namespace RBPDIS_LAB6.Migrations
{
    [DbContext(typeof(RailwayTrafficContext))]
    [Migration("20231212205108_Initial2")]
    partial class Initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RBPDIS_LAB6.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionID")
                        .HasColumnType("int");

                    b.Property<float?>("WorkExperience")
                        .HasColumnType("real");

                    b.HasKey("EmployeeId");

                    b.HasIndex("PositionID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("PositionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("SalaryUsd")
                        .HasColumnType("real");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<TimeSpan?>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<int>("StopId")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("ScheduleId");

                    b.HasIndex("StopId");

                    b.HasIndex("TrainId");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Stop", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StopId"));

                    b.Property<bool?>("HasWaitingRoom")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRailwayStation")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StopId");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Train", b =>
                {
                    b.Property<int>("TrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainId"));

                    b.Property<float?>("DistanceInKm")
                        .HasColumnType("real");

                    b.Property<bool?>("IsBrandedTrain")
                        .HasColumnType("bit");

                    b.Property<string>("TrainNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainTypeId")
                        .HasColumnType("int");

                    b.HasKey("TrainId");

                    b.HasIndex("TrainTypeId");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.TrainStaff", b =>
                {
                    b.Property<int>("TrainStaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainStaffId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("TrainId")
                        .HasColumnType("int");

                    b.HasKey("TrainStaffId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TrainId");

                    b.ToTable("TrainStaffs", (string)null);
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.TrainType", b =>
                {
                    b.Property<int>("TrainTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainTypeId"));

                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainTypeId");

                    b.ToTable("TrainTypes");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Employee", b =>
                {
                    b.HasOne("RBPDIS_LAB6.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Schedule", b =>
                {
                    b.HasOne("RBPDIS_LAB6.Models.Stop", "Stop")
                        .WithMany("Schedules")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RBPDIS_LAB6.Models.Train", "Train")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stop");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Train", b =>
                {
                    b.HasOne("RBPDIS_LAB6.Models.TrainType", "TrainType")
                        .WithMany("Trains")
                        .HasForeignKey("TrainTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainType");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.TrainStaff", b =>
                {
                    b.HasOne("RBPDIS_LAB6.Models.Employee", "Employee")
                        .WithMany("TrainStaffs")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RBPDIS_LAB6.Models.Train", "Train")
                        .WithMany("TrainStaffs")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Employee", b =>
                {
                    b.Navigation("TrainStaffs");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Stop", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.Train", b =>
                {
                    b.Navigation("Schedules");

                    b.Navigation("TrainStaffs");
                });

            modelBuilder.Entity("RBPDIS_LAB6.Models.TrainType", b =>
                {
                    b.Navigation("Trains");
                });
#pragma warning restore 612, 618
        }
    }
}
